spring:
  profiles:
    #运行的环境，多环境配置
    active: test
  application:
    name: Kai-Project
  datasource:
    url: jdbc:mysql://${kproject.mysql.ip}:${kproject.mysql.port}/${kproject.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${kproject.mysql.username}
    password: ${kproject.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      # 前端返回data类型的时候自动转成时间戳
      write-dates-as-timestamps: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl